# Generated by Django 4.1.3 on 2023-01-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'crypto_exchange',
            },
        ),
        migrations.CreateModel(
            name='CryptoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crypto_token',
            },
        ),
    ]
