# Generated by Django 4.1.3 on 2023-01-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=255)),
                ('total', models.IntegerField(default=100000)),
                ('number_request', models.IntegerField()),
            ],
            options={
                'db_table': 'blockchair_request',
            },
        ),
    ]
