# Generated by Django 4.1.3 on 2023-01-07 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertelegramtracker',
            old_name='token_tracker',
            new_name='commands',
        ),
        migrations.RemoveField(
            model_name='usertelegramtracker',
            name='expired_date',
        ),
        migrations.AddField(
            model_name='usertelegramtracker',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertelegramtracker',
            name='step_current',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertelegramtracker',
            name='text_input',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
