# Generated by Django 4.1.3 on 2023-01-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_token_tracker_usertelegramtracker_commands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertelegramtracker',
            name='uuid',
        ),
    ]
