# Generated by Django 4.1.3 on 2023-01-07 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usertelegramtracker_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegramtracker',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 13, 59, 8, 231760, tzinfo=datetime.timezone.utc)),
        ),
    ]
