# Generated by Django 4.1.3 on 2023-01-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_usertelegramtracker_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=15, null=True)),
                ('symbol', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('running', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_token_trigger',
            },
        ),
    ]
