# Generated by Django 4.1.3 on 2023-01-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usertokentrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokentrigger',
            name='name',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
